name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  frontend-build:
    name: Build Angular Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Angular Application
        working-directory: frontend
        run: npm run build


  backend-build:
    name: Build NestJS Backend  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json 

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Build NestJS Application
        working-directory: backend
        run: npm run build